/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as BlogsRouteImport } from './app/blogs'
import { Route as UidRouteImport } from './app/$uid'
import { Route as IndexRouteImport } from './app/index'
import { Route as TeamMembersUidRouteImport } from './app/team-members/$uid'
import { Route as SitemapXmlRouteImport } from './app/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './app/robots.txt'
import { Route as PracticeAreasUidRouteImport } from './app/practice-areas/$uid'
import { Route as OurFirmUidRouteImport } from './app/our-firm/$uid'
import { Route as NewsUidRouteImport } from './app/news/$uid'
import { Route as BlogsUidRouteImport } from './app/blogs/$uid'
import { Route as ApiSendApplicationRouteImport } from './app/api/send-application'
import { Route as ApiRevalidateRouteImport } from './app/api/revalidate'
import { Route as ApiPreviewRouteImport } from './app/api/preview'
import { Route as ApiExitPreviewRouteImport } from './app/api/exit-preview'
import { Route as ApiBlogsRouteImport } from './app/api/blogs'

const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const UidRoute = UidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMembersUidRoute = TeamMembersUidRouteImport.update({
  id: '/team-members/$uid',
  path: '/team-members/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasUidRoute = PracticeAreasUidRouteImport.update({
  id: '/practice-areas/$uid',
  path: '/practice-areas/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const OurFirmUidRoute = OurFirmUidRouteImport.update({
  id: '/our-firm/$uid',
  path: '/our-firm/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsUidRoute = NewsUidRouteImport.update({
  id: '/news/$uid',
  path: '/news/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsUidRoute = BlogsUidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => BlogsRoute,
} as any)
const ApiSendApplicationRoute = ApiSendApplicationRouteImport.update({
  id: '/api/send-application',
  path: '/api/send-application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExitPreviewRoute = ApiExitPreviewRouteImport.update({
  id: '/api/exit-preview',
  path: '/api/exit-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$uid': typeof UidRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/api/blogs': typeof ApiBlogsRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/send-application': typeof ApiSendApplicationRoute
  '/blogs/$uid': typeof BlogsUidRoute
  '/news/$uid': typeof NewsUidRoute
  '/our-firm/$uid': typeof OurFirmUidRoute
  '/practice-areas/$uid': typeof PracticeAreasUidRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/team-members/$uid': typeof TeamMembersUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$uid': typeof UidRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/api/blogs': typeof ApiBlogsRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/send-application': typeof ApiSendApplicationRoute
  '/blogs/$uid': typeof BlogsUidRoute
  '/news/$uid': typeof NewsUidRoute
  '/our-firm/$uid': typeof OurFirmUidRoute
  '/practice-areas/$uid': typeof PracticeAreasUidRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/team-members/$uid': typeof TeamMembersUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$uid': typeof UidRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/api/blogs': typeof ApiBlogsRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/send-application': typeof ApiSendApplicationRoute
  '/blogs/$uid': typeof BlogsUidRoute
  '/news/$uid': typeof NewsUidRoute
  '/our-firm/$uid': typeof OurFirmUidRoute
  '/practice-areas/$uid': typeof PracticeAreasUidRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/team-members/$uid': typeof TeamMembersUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$uid'
    | '/blogs'
    | '/api/blogs'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/api/send-application'
    | '/blogs/$uid'
    | '/news/$uid'
    | '/our-firm/$uid'
    | '/practice-areas/$uid'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/team-members/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$uid'
    | '/blogs'
    | '/api/blogs'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/api/send-application'
    | '/blogs/$uid'
    | '/news/$uid'
    | '/our-firm/$uid'
    | '/practice-areas/$uid'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/team-members/$uid'
  id:
    | '__root__'
    | '/'
    | '/$uid'
    | '/blogs'
    | '/api/blogs'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/api/send-application'
    | '/blogs/$uid'
    | '/news/$uid'
    | '/our-firm/$uid'
    | '/practice-areas/$uid'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/team-members/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UidRoute: typeof UidRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ApiBlogsRoute: typeof ApiBlogsRoute
  ApiExitPreviewRoute: typeof ApiExitPreviewRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  ApiSendApplicationRoute: typeof ApiSendApplicationRoute
  NewsUidRoute: typeof NewsUidRoute
  OurFirmUidRoute: typeof OurFirmUidRoute
  PracticeAreasUidRoute: typeof PracticeAreasUidRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  TeamMembersUidRoute: typeof TeamMembersUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$uid': {
      id: '/$uid'
      path: '/$uid'
      fullPath: '/$uid'
      preLoaderRoute: typeof UidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-members/$uid': {
      id: '/team-members/$uid'
      path: '/team-members/$uid'
      fullPath: '/team-members/$uid'
      preLoaderRoute: typeof TeamMembersUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/$uid': {
      id: '/practice-areas/$uid'
      path: '/practice-areas/$uid'
      fullPath: '/practice-areas/$uid'
      preLoaderRoute: typeof PracticeAreasUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-firm/$uid': {
      id: '/our-firm/$uid'
      path: '/our-firm/$uid'
      fullPath: '/our-firm/$uid'
      preLoaderRoute: typeof OurFirmUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$uid': {
      id: '/news/$uid'
      path: '/news/$uid'
      fullPath: '/news/$uid'
      preLoaderRoute: typeof NewsUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$uid': {
      id: '/blogs/$uid'
      path: '/$uid'
      fullPath: '/blogs/$uid'
      preLoaderRoute: typeof BlogsUidRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/api/send-application': {
      id: '/api/send-application'
      path: '/api/send-application'
      fullPath: '/api/send-application'
      preLoaderRoute: typeof ApiSendApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exit-preview': {
      id: '/api/exit-preview'
      path: '/api/exit-preview'
      fullPath: '/api/exit-preview'
      preLoaderRoute: typeof ApiExitPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsUidRoute: typeof BlogsUidRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsUidRoute: BlogsUidRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UidRoute: UidRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ApiBlogsRoute: ApiBlogsRoute,
  ApiExitPreviewRoute: ApiExitPreviewRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  ApiSendApplicationRoute: ApiSendApplicationRoute,
  NewsUidRoute: NewsUidRoute,
  OurFirmUidRoute: OurFirmUidRoute,
  PracticeAreasUidRoute: PracticeAreasUidRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  TeamMembersUidRoute: TeamMembersUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
