// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  benefit_headline: dynamic(() => import("./BenefitHeadline")),
  blog_index: dynamic(() => import("./BlogIndex")),
  color_grid: dynamic(() => import("./ColorGrid")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  featured: dynamic(() => import("./Featured")),
  four_cards_section: dynamic(() => import("./SalesInfo")),
  hero: dynamic(() => import("./Hero")),
  journey_end: dynamic(() => import("./JourneyEnd")),
  newsletter_slice: dynamic(() => import("./NewsletterSlice")),
  plan_info: dynamic(() => import("./PlanInfo")),
  services: dynamic(() => import("./Services")),
  text_block: dynamic(() => import("./TextBlock")),
};
