// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_index: dynamic(() => import("./BlogIndex")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  hero: dynamic(() => import("./Hero")),
  text_block: dynamic(() => import("./TextBlock")),
};
