// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  hero: dynamic(() => import("./Hero")),
};
